add wave -position end  sim:/icache_tb/DUT/SETS
add wave -position end  sim:/icache_tb/DUT/BLKS_PER_SET
add wave -position end  sim:/icache_tb/DUT/WORDS_PER_BLK
add wave -position end  sim:/icache_tb/DUT/CLK
add wave -position end  sim:/icache_tb/DUT/nRST
add wave -position end  sim:/icache_tb/DUT/iaddr
add wave -position end  sim:/icache_tb/DUT/sets
add wave -position end  sim:/icache_tb/DUT/set_sel
add wave -position end  sim:/icache_tb/DUT/block_sel
add wave -position end  sim:/icache_tb/DUT/data_sel
add wave -position end  sim:/icache_tb/DUT/cache_write
add wave -position end  sim:/icache_tb/DUT/nxt_data
add wave -position end  sim:/icache_tb/DUT/mem_ready
add wave -position end  sim:/icache_tb/DUT/ihit
add wave -position end  sim:/icache_tb/DUT/miss
add wave -position end  sim:/icache_tb/DUT/cur_state
add wave -position end  sim:/icache_tb/DUT/nxt_state