add wave -position insertpoint -group TB sim:/system_tb/*
add wave -position insertpoint -group CM sim:/system_tb/DUT/CPU/CM/*
add wave -position insertpoint -group Cache-Control sim:/system_tb/DUT/CPU/CC/ccif/*
add wave -position insertpoint -group DP-Cache sim:/system_tb/DUT/CPU/dcif/*
add wave -position insertpoint -group Datapath sim:/system_tb/DUT/CPU/DP/*
add wave -position insertpoint -group Datapath sim:/system_tb/DUT/CPU/DP/dpif/*
add wave -position insertpoint -group ControlUnit sim:/system_tb/DUT/CPU/DP/cuif/*
add wave -position insertpoint -group ALU sim:/system_tb/DUT/CPU/DP/ALU/aluif/*
add wave -position insertpoint -group RegisterFile sim:/system_tb/DUT/CPU/DP/RF/rfif/*
add wave -position insertpoint -group RegisterFile sim:/system_tb/DUT/CPU/DP/RF/register
add wave -position insertpoint -group RAM  sim:/system_tb/DUT/RAM/ramif/*
add wave -position insertpoint -group PCIF sim:/system_tb/DUT/CPU/DP/pcif/*
add wave -position insertpoint -group HazardUnit sim:/system_tb/DUT/CPU/DP/huif/*
#add wave -position insertpoint -group PLIF sim:/system_tb/DUT/CPU/DP/plif/*
add wave -position insertpoint -group Fetch-Decode sim:/system_tb/DUT/CPU/DP/fdif/*
add wave -position insertpoint -group Decode-Execute sim:/system_tb/DUT/CPU/DP/deif/*
add wave -position insertpoint -group Execute-Mem sim:/system_tb/DUT/CPU/DP/emif/*
add wave -position insertpoint -group Mem-WriteBack sim:/system_tb/DUT/CPU/DP/mwif/*
#add wave -position insertpoint -group FUIF sim:/system_tb/DUT/CPU/DP/fuif/*
